var exercises = ['Cable Pushdown', 
'Dumbbell Standing Preacher Curl', 
'Barbell Wide Squat', 
'Cable Standing Rear Delt Horizontal Row', 
'Cable Two Arm Tricep Kickback', 
'Lever Standing Hip Extension', 
'Dumbbell Incline Twisted Flyes', 
'Lever Chest Press (plate loaded)', 
'Dumbbell Incline Bench Press', 
'Crunch (on bench)', 
'Dumbbell Behind Back Finger Curl', 
'Dip on Floor with Chair', 
'Lever Incline Chest Press (plate loaded)', 
'Barbell Rear Lunge (without weight)', 
'Dumbbell Press Squat', 
'Dumbbell Single Leg Calf Raise', 
'Barbell Incline Shoulder Raise', 
'Dumbbell One Arm Reverse Preacher Curl', 
'Dumbbell Single Leg Deadlift', 
'Lever Seated Squat', 
'Cable Standing Reverse Grip Curl (Straight bar)', 
'Circles Elbow Arm', 
'Side Lunge', 
'Cable kickback', 
'Dumbbell Seated Inner Biceps Curl', 
'Forearm   Supination', 
'Dumbbell forward leaning lunge', 
'Kettlebell Step up (VERSION 2)', 
'Barbell Good Morning', 
'Dumbbell Alternate Biceps Curl_1', 
'Dumbbell Incline reverse grip 30 degrees bench press', 
'Lever Bicep Curl', 
'Cable One Arm High Pulley Overhead Tricep Extension', 
'Barbell Full squat (with rack)', 
'Reverse Lunge (leg kick)', 
'Self assisted Inverse Leg Curl', 
'Barbell Walk Calves Activation', 
'Band one arm overhead biceps curl', 
'Dumbbell One Arm Chest Fly on Exercise Ball', 
'Cross Body Twisting Crunch', 
'Self Assisted Inverse Leg Curl (VERSION 2)', 
'Barbell Stiff Legged Deadlift', 
'Sled 45 Leg Press (Back POV)', 
'Barbell Hip Thrust', 
'Weighted Squat', 
'Lever Seated Leg Press', 
'Kick out Sit (wall)', 
'Plate Hyperextension', 
'Cable Supine Reverse Fly', 
'Assisted Chest Dip (kneeling)', 
'Kettlebell Russian Twist', 
'Front Plank_1', 
'Band Low Chest Fly', 
'Handstand', 
'Dumbbell Squat', 
'Weighted Russian Twist (legs up)', 
'Smith Front Squat (Clean Grip)', 
'Band standing chest press', 
'Jump Squat II', 
'Barbell Spider Curl', 
'Band Standing Straight Arm Pulldown_1', 
'Lever Triceps Extension', 
'Lever Seated Leg Press (VERSION 2)', 
'Barbell Prone Incline Curl', 
'Barbell Floor Chest Press', 
'Band standing rear delt row', 
'Bodyweight Standing Biceps Curl', 
'EZ Barbell Close grip Curl', 
'Dumbbell Decline Hammer Press', 
'Cable Curl with Multipurpose V bar', 
'Dumbbell One arm Revers Wrist Curl', 
'Cable Front Seated Row', 
'Cable Reverse grip Pushdown', 
'Cable Seated Supine grip Row', 
'Dumbbell One Arm Seated Neutral Wrist Curl', 
'Dumbbell Over Bench One Arm Wrist Curl', 
'Dumbbell Incline Rear Lateral Raise', 
'Dumbbell Neutral Grip Bench Press', 
'3 4 Sit up', 
'Reverse Crunch m', 
'Band Biceps Curl', 
'test_1', 
'Band Knelling Lat Pulldown', 
'Dumbbell Full Can Lateral Raise', 
'Bent Leg Kickback (kneeling)', 
'Glute Bridge March', 
'Assisted Hanging Knee Raise', 
'Hanging Leg Hip Raise', 
'Leg Raise Hip Lift', 
'Cable Seated Shoulder Internal Rotation', 
'Dumbbell Romanian Deadlift', 
'Lever Chest Press (VERSION 2)', 
'Dumbbell Seated Preacher Curl', 
'Self assisted Inverse Leg Curl (on floor)', 
'Lever Lying Leg Curl', 
'Cobra Push up', 
'Barbell Bench Front Squat', 
'Barbell Incline Close Grip Bench Press', 
'Narrow Squat from Deficit', 
'Dumbbell One Arm Reverse Fly (with support)', 
'Finger Curls', 
'Barbell Close Grip Bench Press', 
'Dumbbell Close Grip Shoulder Press Sit up', 
'Dumbbell Alternating Floor Press', 
'Suspender Squat', 
'Dumbbell Devils Press', 
'Lever Seated Crunch (chest pad)', 
'Knuckle Push Up', 
'Lever Incline Chest Press', 
'Lunge with Leg Lift', 
'Band overhead triceps extension (VERSION 2)', 
'Isometric Wipers', 
'Arm Circles', 
'Barbell JM Bench Press', 
'Bench Pull ups', 
'Cable Standing One Arm Triceps Extension', 
'Back lever_1', 
'Cable Lateral Pulldown with V bar', 
'Cable Reverse Grip Pulldown', 
'Dumbbell Seated Reverse Grip One Arm Overhead Tricep Extension', 
'Barbell Incline Wide Reverse grip Bench Press', 
'Front Plank Toe Tap', 
'Dumbbell Seated Alternate Shoulder Press', 
'Cable One Arm Lateral Bent over', 
'Cable Triceps Pushdown (SZ bar)', 
'Lever Alternate Leg Extension (plate loaded)', 
'Dumbbell Incline Press on Exercise Ball', 
'Side Bridge', 
'Lever Leg Extension', 
'Weighted Crunch', 
'Resistance Band Seated Single Leg Curl', 
'Barbell Seated Behind Head Military Press', 
'Barbell Decline Close Grip To Skull Press', 
'Dips between Chairs', 
'Cable Standing High Cross Triceps Extension', 
'Cable Decline Fly', 
'Cable Concentration Extension (on knee)', 
'Barbell Side Bent II', 
'EZ Barbell Reverse Grip Curl', 
'Kettlebell One Legged Deadlift', 
'Barbell Clean and Press', 
'Dumbbell Bent Arm Pullover Hold', 
'Kettlebell Backward Lunge', 
'Barbell Incline Row', 
'Dumbbell Seated Reverse Grip Biceps Curl', 
'Archer Push up', 
'Resistance Band Leg Curl', 
'Barbell Overhead Squat', 
'Bodyweight Wall Squat', 
'Resistance Band Seated Biceps Curl', 
'Cable Standing Alternate Low Fly', 
'Dumbbell Prone Incline Curl', 
'Dumbbell Curtsey lunge', 
'Band standing external shoulder rotation', 
'Dumbbell Step Up Single Leg Balance with Bicep Curl', 
'Kettlebell Kickstand One Leg Deadlift', 
'Lever One Leg Extension', 
'Dumbbell Lying Triceps Extension_1', 
'Dumbbell Over Bench Revers Wrist Curl', 
'Barbell Full Squat', 
'Hanging Toes to Bar', 
'Lying Double Legs Biceps Curl with Towel', 
'Single Leg Extension (on stability ball)', 
'Dumbbell Seated Front Raise', 
'Barbell Standing Rocking Leg Calf Raise', 
'Lever Rotary Calf', 
'Assisted Chin up', 
'Seated Flutter Kick', 
'Cable One Arm Curl', 
'Barbell Shrug', 
'Cable Seated Horizontal Shrug', 
'Barbell Preacher Curl', 
'Cable High Triceps Extension', 
'EZ bar 21s', 
'Dumbbell One Arm Seated Hammer Curl', 
'Barbell Pin Presses', 
'Cable Overhead Tricep Extension Straight Bar', 
'Dumbbell Floor Fly', 
'Crunch (hands overhead)', 
'Cable Seated High Row (V bar)', 
'Bodyweight Bent Over Rear Delt Fly', 
'Dumbbell Seated Lateral Raise', 
'Cable One Arm Biceps Curl (VERSION 2)', 
'Assisted Wide Grip Chest Dip (kneeling)', 
'Ankle Circles', 
'Dumbbell Goblet Box Squat', 
'Split Lateral Squat with Roll', 
'Triceps Dips Floor', 
'Cable Rear Delt Row', 
'Dumbbell Hammer Curl', 
'Barbell Bent Over Wide Grip Row', 
'Donkey Calf Raise', 
'Assisted Inverse Leg Curl', 
'Cable Standing One Arm Tricep Pushdown (Overhand Grip)', 
'Barbell Palms Up Wrist Curl Over A Bench', 
'Squat mobility Complex', 
'Smith Close Grip Bench Press', 
'Deep Push Up', 
'Resistance Band Bent Leg Side Kick (kneeling)', 
'Reverse Plank with Leg Lift', 
'Dumbbell Incline Bench Press_1', 
'Cable One Arm Straight Back High Row (kneeling)', 
'Lever Lying Single Leg Curl', 
'Cable Decline Seated Wide Grip Row', 
'Lever Back Extension (version 2)', 
'Barbell Decline Pullover', 
'Weighted Frog Pump', 
'Lever Seated Hip Adduction (VERSION 2)', 
'Modified Push Up to Forearms', 
'Resistance Band Hammer Curl', 
'Cable Incline Pushdown', 
'Dumbbell Gobelt Curtsey Lunge', 
'Cable Rope Extension Incline Bench Row', 
'Safety Bar Front Squat', 
'Dumbbell One Arm Reverse Grip Press', 
'Cable Half Kneeling Push Pull', 
'EZ Barbell Incline Triceps Extension', 
'Lever Incline Hammer Chest Press', 
'Kettlebell Swing', 
'Smith Sumo Squat', 
'Cable Lying Upright Row', 
'Cable Upright Row', 
'Dumbbell Seated Neutral Wrist Curl', 
'Lever Preacher Curl (plate loaded)_1', 
'Landmine Rear Lunge', 
'Lever Standing Rear Kick', 
'Dumbbell Concentration Curl', 
'Dumbbell Half Kneeling Military Press', 
'Roll Seated Single Leg Shoulder Flexor Depresor Retractor', 
'Cable Bent Over Reverse Grip Row', 
'Dumbbell Side Lunge (VERSION 3)', 
'Cable Bench Press', 
'Cable Triceps Pushdown (V bar) (VERSION 2)', 
'Incline Push up', 
'Side Bridge (knee tuck)', 
'Barbell Rear Delt Row', 
'Reverse Push up', 
'Triceps Dip', 
'Standing Gastrocnemius', 
'Cable Reverse grip Straight Back Seated High Row', 
'Cable Overhead Triceps Extension (rope attachment)', 
'Dumbbell Rear Lateral Raise (support head)', 
'Glute Ham Raise (VERSION 2)', 
'Crab Twist Toe Touch', 
'Barbell Squat (on knees)', 
'Dumbbell Low Fly', 
'Body Saw Plank', 
'Dumbbell Two Arm Seated Hammer Curl on Exercise Ball', 
'Weighted Seated Triceps Extension', 
'Dumbbell Seated Revers grip Concentration Curl', 
'Cable Straight Arm Pulldown', 
'Bodyweight Kneeling Sissy Squat', 
'Lever Donkey Calf Raise', 
'Dumbbell Alternate Preacher Curl', 
'Weighted Seated Reverse Wrist Curl', 
'Band Pull Apart', 
'Band Upright Shoulder External Rotation', 
'Resistance Band Assisted Nordic Hamstring Curl', 
'Lever Banded Chest Press', 
'Cable Standing Chest Press', 
'Assisted Prone Hamstring', 
'Barbell Bench Press', 
'Alternate Lateral Pulldown_1', 
'Dumbbell Biceps Curl Reverse', 
'Barbell Rear Lunge', 
'Dumbbell One Arm Standing Curl', 
'Dumbbell Seated Bicep Curl', 
'Ankle   Dorsal Flexion', 
'Barbell Side Split Squat II', 
'Barbell Pullover', 
'Barbell Palms Down Wrist Curl Over A Bench', 
'Elbow to Knee', 
'Smith Bent Knee Good morning', 
'Barbell Standing Calf Raise', 
'Hip Raise (bent knee)', 
'Barbell Straight Leg Deadlift', 
'Band Standing Single Arm Row_1', 
'Ankle   Plantar Flexion', 
'Landmine Romanian Deadlift', 
'Hip Roll Plank', 
'Dumbbell RDL Death March', 
'Resistance Band Plank March', 
'Band reverse fly', 
'Dumbbell One Arm Shoulder Press II', 
'Alternate Biceps Curl (with band)', 
'Dumbbell Bench Seated Press', 
'Lever Lying Two One Leg Curl', 
'Twist Crunch (leg up)', 
'Cable Seated One Arm Concentration Curl', 
'Cable Front Squat (VERSION 2)', 
'EZ bar Biceps Curl (with arm blaster)', 
'Cable Middle Fly', 
'Barbell Single Leg Split Squat', 
'Band standing leg curl', 
'Weighted Sissy Squat', 
'Dumbbell Seated Hammer Curl', 
'Lever Seated Squat Calf Raise on Leg Press Machine', 
'Diamond Press', 
'Trap Bar Deadlift', 
'Cable Bent Over Row with Rope Attachment', 
'Kettlebell Sumo Squat', 
'Barbell Standing Wide grip Curl', 
'Side Crunch II', 
'Cable Cross over Revers Fly', 
'Dumbbell One Arm Shoulder Press', 
'Cable Kneeling Leaning Forward One Arm Row', 
'Forward Lunge', 
'Sled Lying Squat', 
'Dumbbell Lying Hammer Press', 
'Smith Seated Wrist Curl', 
'Dumbbell One Arm Kickback', 
'Lever Chair Squat', 
'Lever Crossovers', 
'Superman Row with Towel', 
'Barbell Standing Reverse Grip Curl', 
'Weighted Cossack Squats', 
'Cable Hammer Curl', 
'Barbell Seated Shrug', 
'Band face pull', 
'Superman', 
'Dumbbell Standing Concentration Curl', 
'Cable Seated Pullover', 
'Smith Standing Back Wrist Curl', 
'Dumbbell Alternate Seated Hammer Curl', 
'Push up on Forearms', 
'Finger Push up', 
'Russian Twist', 
'Barbell Behind Back Finger Curl', 
'Dumbbell Lunge (VERSION 2)', 
'Cable Standing Back Wrist Curl', 
'Weighted Seated Supination', 
'Dumbbell Lunge_1', 
'Dumbbell Over Bench One Arm  Neutral Wrist Curl', 
'Barbell Lunge', 
'Dumbbell One Arm Snatch', 
'Barball Pullover To Press', 
'Dumbbell Overhead Squat', 
'Dumbbell Alternate Hammer Preacher Curl', 
'Cable Wrist Curl', 
'Cable Reverse Grip Triceps Pushdown (with arm blaster)', 
'Cable Curl', 
'Kettlebell One Arm Overhead Squat', 
'Cable Kneeling Rear Delt Row (with rope)', 
'Dumbbell One Arm Lateral Raise_1', 
'Barbell Decline Bench Press', 
'Dumbbell Front Rack Lunge', 
'Balance Board', 
'Cable One Arm Reverse Fly', 
'Dumbbell Deadlift', 
'Dumbbell Fly (knees at 90 degrees)', 
'Lever Deadlift (plate loaded)', 
'Dumbbell Alternate Biceps Curl', 
'Dumbbell Incline Shoulder Raise', 
'Lever Horizontal One leg Press', 
'Bodyweight Squatting Row (with towel)', 
'Lying Leg Raise and Hold', 
'Dumbbell Cross Body Hammer Curl (Version 2)', 
'Band Seated Leg Extension', 
'Cable Assisted Inverse Leg Curl', 
'Bodyweight Pulse Squat', 
'Curtsey Squat', 
'Cable Drag Curl', 
'Kettlebell Goblet Squat Mobility', 
'Kettlebell Pistol Squat', 
'Band Lateral Raise (Version 2)', 
'Dumbbell Goblet Split Squat', 
'Lever Seated Hip Abduction (VERSION 2)', 
'Dumbbell Alternate Bench Press (high start)', 
'Cable kickback II', 
'Kicks Leg Bent', 
'Cable Bent Over One Arm Lateral Raise', 
'Dumbbell Over Bench Neutral Wrist Curl', 
'Barbell Bent Arm Pullover', 
'Barbell Seated Good morning', 
'Lying Scissor Kick', 
'Cable Overhead Curl', 
'Assisted Triceps Dip', 
'Chest Dip', 
'Dumbbell side lunge', 
'Squat (arms overhead)', 
'Suspender Straight Hip Leg Curl', 
'Dumbbell Seated One Arm Arnold Press', 
'Barbell Reverse Grip Incline Bench Row', 
'Lever Chest Press', 
'Dumbbell Decline Bench Press_1', 
'Cable Incline Fly', 
'Archer Pull up_1', 
'Suspender Leg Curl', 
'Band straight leg deadlift_1', 
'Assisted Pullup (Neutral grip)', 
'Cable Seated on Floor Row with Rope', 
'Cable One Arm Side Triceps Pushdown', 
'Cable Incline Cross Rear Fly', 
'Step up on Chair', 
'Barbell Full Squat (without weight)', 
'Crunch Floor m', 
'Band One Arm Twisting Seated Row', 
'Cable Lying Cross Lateral Raise', 
'Dumbbell Reverse Fly', 
'Cable Seated Curl', 
'Hyght Dumbbell Fly', 
'Cable Upper Chest Crossovers', 
'Barbell Rear Delt Raise', 
'Band Close Grip Row', 
'Single Leg Squat (pistol) male', 
'Dumbbell Lateral Raise', 
'Dumbbell Alternate Biceps Curl (with arm blaster)', 
'Dumbbell Lying One Arm Supinated Triceps Extension', 
'Dumbbell Bench Squat', 
'Cable Lying Triceps Extension', 
'Dumbbell Seated Triceps Extension', 
'Barbell Lying Back of the Head Tricep Extension', 
'Barbell Lying Close Grip Underhand Row on Rack', 
'Bulgarian Split Squat', 
'Dumbbell Lying Pronation on Floor', 
'Cable Low Fly_1', 
'Cable Fly with Chest Supported', 
'Assisted Pull up (Overhand)', 
'Cable one arm lat pulldown', 
'Barbell Reverse Curl', 
'Lever Leg Extension (plate loaded)', 
'Band Standing Hammer Curl', 
'Cable Kneeling Crunch', 
'Dumbbell Lying on Floor Hammer Press', 
'EZ Bar Standing French Press', 
'Dumbbell Incline Fly', 
'Smith Low Bar Squat', 
'Tiger Tail Hamstring', 
'Sled Calf Press On Leg Press', 
'Dumbbell Lunge', 
'Lever Hip Extension (VERSION 2)', 
'Cable Incline Skull Crusher', 
'Barbell Decline wide grip pullover', 
'Dumbbell Over Bench One Arm Reverse Wrist Curl', 
'Cable Lying Biceps Curl (VERSION 2)', 
'Dumbbell Flat Around the World', 
'Barbell Jump Squat', 
'Cable Lateral Pulldown (with rope attachment)', 
'Cable High Pulley Overhead Tricep Extension', 
'Dumbbell Sumo Squat (back on stability ball wall)', 
'Smith Full Squat', 
'Barbell Incline Triceps Extension Skull Crusher', 
'Cable Hammer Curl (with rope) m', 
'Single Leg Deadlift with Knee Lift', 
'Cable Squatting Curl', 
'Bent Knee Side Plank', 
'Kettlebell One Arm Floor Press', 
'Cable Alternate Triceps Extension', 
'Scissors (advanced)', 
'Single Leg Sliding Floor Bridge Curl on Towel', 
'Band reverse wrist curl', 
'Barbell Standing Close Grip Curl', 
'Dumbbell Bar Grip Sumo Squat', 
'Smith rear lunge (version 2)', 
'Lever Seated Calf Press', 
'Resistance Band Bent Leg Kickback (Kneeling)', 
'Barbell Standing Wide Military Press', 
'Lever Standing Calf Raise', 
'Barbell Wide Grip Upright Row', 
'Barbell Reverse Preacher Curl', 
'Barbell Reverse Grip Bent over Row', 
'Barbell Standing Military Press', 
'Smith Calf Raise (version 2)', 
'Barbell Standing Front Raise Over Head', 
'Barbell Lying Row on Rack', 
'Squat m', 
'Lying Scissor Crunch', 
'Dumbbell Incline Curl', 
'Kneeling Hip Flexor', 
'Leg Curl (on stability ball)', 
'Cable Rope Hammer Preacher Curl', 
'Band kneeling one arm pulldown', 
'EZ Bar California Skullcrusher', 
'Sled One Leg Calf Press on Leg Press', 
'Dumbbell One Arm Low Fly', 
'Battling Ropes High Waves', 
'Dumbbell Squeeze Bench Press', 
'Barbell Standing Military Press (without rack)', 
'One Leg Quarter Squat', 
'Bar Band Bent Over Rear Delt Fly', 
'Butt ups', 
'Dumbbell Alternate Arnold Press', 
'Smith Machine Incline Tricep Extension', 
'Barbell Bench Squat', 
'Cable One Arm Pulldown', 
'EZ Barbell Curl', 
'Barbell Sumo Deadlift', 
'Cable Seated Chest Press', 
'Bridge   Mountain Climber (Cross Body)', 
'Lever Preacher Curl', 
'Lunge', 
'Kettlebell Front Squat', 
'Barbell Seated Overhead Triceps Extension', 
'Dumbbell Incline T Raise', 
'Bodyweight Side Lying Biceps Curl', 
'Clock Push Up', 
'Decline Push Up m', 
'Band overhead triceps extension', 
'Cocoons', 
'Dumbbell Reverse Preacher Curl', 
'Cable One Arm Tricep Pushdown', 
'Kettlebell Bottoms Up Clean From The Hang Position', 
'Seated Leg Raise', 
'Dumbbell Standing Single Spider Curl', 
'Dumbbell Split Squat', 
'Cable Shoulder Press', 
'Dumbbell Incline Close grip Press Variation', 
'Cable Low Fly', 
'Resistance Band Leg Extension', 
'Weighted one leg hip thrust', 
'EZ Barbell Seated Triceps Extension', 
'Dumbbell Seated One Leg Calf Raise', 
'Dumbbells Seated Triceps Extension', 
'Dumbbell Around Pullover', 
'Cable Triceps Pushdown (V bar) (with arm blaster)', 
'Hack Calf Raise', 
'Dumbbell Crunch Up', 
'Dumbbell Push Press', 
'Smith Chair Squat', 
'Dumbbell Clean', 
'Hand Spring Wrist Curl', 
'45 degree hyperextension (arms in front of chest) (Side POV)', 
'Crunch (arms straight)', 
'Trap Bar Split Stance RDL', 
'Dumbbell Rear Fly', 
'Barbell Curl (without weight)', 
'Weighted Kneeling Step with Swing', 
'Bodyweight Drop Jump Squat', 
'Sit (wall)', 
'Cable Close Grip Front Lat Pulldown', 
'Dumbbell Prone Incline Hammer Curl', 
'Dumbbell Seated One Arm Shoulder Press', 
'Barbell Bent Over Row', 
'Barbell Front Raise and Pullover', 
'Dumbbell Bench Press_1', 
'Band Assisted Chin Up (From Knee)_1', 
'Dumbbell Incline Curl II', 
'Wrist   Extension', 
'Dumbbell Rear Lunge', 
'Resistance Band Full Squat', 
'Sliding Leg Curl on Floor with Towel', 
'Smith Lateral Step Up', 
'EZ bar Close Grip Bench Press', 
'Cable Overhead Single Arm Triceps Extension (rope attachment)', 
'Barbell Wide Reverse Grip Bench Press', 
'Cable Standing Face Pull (with rope)', 
'Dumbbell Incline Alternate Bicep Curl', 
'Cable Rear Delt Row (with rope)', 
'Dumbbell Incline Y Raise', 
'Cable Rope One Arm Hammer Preacher Curl', 
'Cable Deadlift', 
'Single Leg Platform Slide', 
'Weighted Seated Calf Raise', 
'Barbell Lying extension', 
'Cable Palm Rotational Row', 
'Circles Arm', 
'dark_1', 
'Sled 45 Leg Wide Press', 
'Lever Seated Leg Curl', 
'Barbell Front Squat', 
'Roll Body Saw', 
'Cable Seated Rear Lateral Raise', 
'Decline Bent Leg Reverse Crunch', 
'Band Overhead Single Arm Triceps Extension', 
'Cable Kneeling One Arm Lat Pulldown', 
'Hollow Hold', 
'Negative Crunch', 
'Dumbbell Seated Palms Up Wrist Curl', 
'Barbell Glute Bridge', 
'Cable Pull Through (with rope)', 
'Dumbbell One Arm Zottman Preacher Curl', 
'Dumbbell Close Grip Curl', 
'Wall Ball', 
'Cable Stiff Leg Deadlift from Stepbox', 
'Resistance Band Lateral Walk', 
'Barbell Upright Row (without weight)', 
'Dumbbell Standing Inner Biceps Curl', 
'Band Kneeling Preacher Curl', 
'Dumbbell Drag Bicep Curl', 
'Inverse Leg Curl (bench support)', 
'Dumbbell Alternate Side Press', 
'Cable Lying Fly', 
'Barbell Lying Triceps Extension Skull Crusher', 
'Barbell Deadlift', 
'Handboard Hang with 135 Degree Elbow', 
'Barbell Full Squat (Back POV)', 
'Smith Toe Raise', 
'Alternate Lying Floor Leg Raise', 
'Dumbbell One Arm Bench Fly', 
'EZ Barbell Standing Wide Grip Biceps Curl', 
'Dumbbell Standing Calf Raise', 
'Lever Seated Hip Abduction', 
'Barbell Standing Leg Calf Raise', 
'Barbell Behind The Back Shrug', 
'Cable Close Grip Curl', 
'Barbell Incline Reverse grip Spider Curl with Chest Support', 
'Full Squat Mobility', 
'Biceps Leg Concentration Curl', 
'Barbell Split Squat', 
'Weighted Seated One Arm Reverse Wrist Curl', 
'Band high fly', 
'Barbell High Bar Squat', 
'Cable Floor Seated Wide grip Row', 
'Cable Rope Elevated Seated Row', 
'Dumbbell Split Squat Front Foot Elevanted', 
'Dumbbell One Arm Incline Chest Press', 
'Vertical Leg Raise (on parallel bars)', 
'Weighted Three Bench Dips', 
'Dumbbell Incline Alternate Press', 
'Decline Crunch', 
'Barbell Low Bar Squat', 
'Barbell Floor Calf Raise', 
'Dumbbell one leg squat w', 
'Bodyweight Standing Calf Raise', 
'Lever Alternate Biceps Curl', 
'Lever Seated One Leg Curl', 
'Smith Single Leg Split Squat', 
'Dumbbell Standing Alternating Tricep Kickback', 
'Superman', 
'Dumbbell Standing Inner Biceps Curl (version 2)', 
'EZ Barbell Seated Curls', 
'Cable Standing Wrist Curl', 
'Dumbbell Pullover', 
'Dumbbell Seated One Arm Rotate', 
'Dumbbell Banded Bench Press', 
'Push up', 
'Brachialis Narrow Pull ups', 
'Dumbbell Russian Twist', 
'Dumbbell Twisted Fly', 
'Bodyweight Kneeling Push Up Row', 
'EZ Barbell Decline Triceps Extension', 
'Dumbbell Standing One Arm Reverse Curl', 
'Cable Preacher Curl', 
'Cable Crossover Variation', 
'Barbell Close Grip Bench Press_1', 
'Dumbbell Seated Kickback', 
'Cable One Arm Bent over Row', 
'Kettlebell Alternating Press on Floor', 
'Dumbbell Incline Two Arm Extension', 
'Barbell Romanian Deadlift', 
'Dumbbell Standing Bent Over One Arm Triceps Extension', 
'Cable Standing Fly_1', 
'EZ Bar Lying Close Grip Triceps Extension Behind Head', 
'Weighted Standing Hand Squeeze', 
'Lever Decline Chest Press', 
'Dumbbell Seated Shoulder Press', 
'Cable High Row (kneeling%2C rope attachment)', 
'Bench Dip with legs on bench', 
'Chest Dip (on dip pull up cage)', 
'Reverse Dip', 
'Cable Rope High Pulley Overhead Tricep Extension', 
'Dumbbell Flat Flye Hold', 
'Barbell Sumo Romanian Deadlift', 
'Lever Seated Crunch', 
'Smith Front Squat', 
'Band standing internal shoulder rotation', 
'Band front raise', 
'Band wrist curl', 
'Sled 45 degrees One Leg Press', 
'Dumbbell Decline Triceps Extension', 
'Smith Split Squat', 
'Dumbbell Stiff Leg Deadlift', 
'Smith Seated Calf Raise', 
'Dumbbell Rotation Reverse Fly', 
'Cable Standing Inner Curl', 
'Dumbbell Standing Biceps Curl to Shoulder Press', 
'Band kneeling pulldown', 
'Cable Lying Triceps Extension (with Rope)', 
'Bench Dip (knees bent)', 
'Cable Rope Incline Tricep Extension', 
'Cable Reverse Grip Triceps Pushdown (SZ bar)', 
'Dumbbell Incline Alternate Hammer Curl', 
'Dumbbell Bench Press', 
'Cable Low Seated Row', 
'Dumbbell Front Squat', 
'EZ Bar Seated Close Grip Concentration Curl', 
'Lever Triceps Dip (plate loaded)', 
'Suspender Triceps Extension', 
'Band overhead triceps extension', 
'Barbell Deadlift_1', 
'Bodyweight Standing Pulse Calf Raise', 
'Lever Hip Thrust', 
'Dumbbell Rear Delt Raise', 
'Band middle fly', 
'Barbell Skier', 
'Barbell Front Chest Squat', 
'Barbell Reverse Grip Skullcrusher', 
'Barbell Wrist Curl', 
'Dumbbell Seated Alternate Front Raise', 
'Dumbbell Decline Bench Press', 
'Resistance Band Leg Curl', 
'Lever Preacher Curl (plate loaded)', 
'Barbell Seated Military Press (inside squat cage)', 
'Triceps Dip (bench leg)', 
'Cable Reverse Wrist Curl', 
'Dumbbell Decline Fly', 
'Cable Curl', 
'Squat', 
'Smith Calf Raise (with block)', 
'Cable Reverse Curl', 
'Band bent over rear lateral raise', 
'Dumbbell Lying Single Extension', 
'Hyperextension', 
'Dumbbell Lying Hamstring Curl', 
'Cable Kneeling Single Lat Pulldown', 
'Band Skull Crusher', 
'Sit Up II', 
'Band standing leg curl', 
'Smith Stiff Legged Deadlift', 
'Cable twisting overhead press', 
'Lever Seated Horizontal Leg Press', 
'Cable Twist', 
'Cable Kneeling Triceps Extension', 
'Band reverse curl', 
'Dumbbell Standing Alternate Hammer Curl and Press', 
'Cable standing hip extension (version 2)', 
'Cable Rear Drive', 
'Landmine Floor One Arm Chest Fly', 
'Dumbbell Incline Around the World', 
'Dumbbell Standing Reverse Curl', 
'Cable Seated Row with V bar', 
'Barbell Seated Close grip Concentration Curl', 
'Cable One Arm Preacher Curl', 
'Bridge (straight arm)', 
'Lever Kneeling Leg Curl (plate loaded)', 
'Sit up with Arms on Chest', 
'Assisted Weighted Push up', 
'Dumbbell Peacher Hammer Curl', 
'Hack One Leg Calf Raise', 
'Cable Lying Extension Pullover (with rope attachment)', 
'Side Lying Clam', 
'Cable Seated Rear Delt Fly with Chest Support', 
'Bent Leg Side Kick (kneeling)', 
'Barbell Full Squat (Side POV)', 
'Bodyweight Standing Row', 
'Band side triceps extension', 
'Landmine Front Squat', 
'Plyo Sit Squat (wall)', 
'Dumbbell Cross Body Hammer Curl', 
'Dumbbell Standing Single Leg Calf Raise', 
'Dumbbell Swing', 
'Hanging Leg Raise', 
'Barbell Revers Wrist Curl II', 
'Sumo Squat m', 
'Landmine Kneeling Squeeze Press', 
'Jack Plank', 
'Standing Straight Leg Hamstring Contract Relax on Exercise Ball', 
'Sled 45 Leg Press (Side POV)', 
'Cable Seated Lats Focused Row', 
'Cable Half Kneeling External Rotation', 
'Dumbbell Standing Bent Over Two Arm Triceps Extension', 
'Roll Reverse Crunch', 
'Cable seated row', 
'Dumbbell Incline Inner Biceps Curl', 
'Sled Wide Hack Squat', 
'Cable Standing Calf Raise', 
'Otis Up', 
'Cable Front Shoulder Raise', 
'Band Biceps Curl (2)', 
'Dumbbell Kickback', 
'Sled 45 Calf Press', 
'Band Chest Fly', 
'Barbell Guillotine Bench Press', 
'Barbell sumo squat', 
'Cable Standing Reverse Grip One Arm Overhead Tricep Extension', 
'Barbell Decline Wide grip Press', 
'Dumbbell One Arm Lateral Raise', 
'Dumbbell Front Raise', 
'Cable Reverse Grip Biceps Curl (SZ bar)', 
'Dumbbell Lying Elbow Press', 
'Dumbbell Zottman Curl', 
'Smith One Leg Floor Calf Raise', 
'Dumbbell One Arm Concetration Curl (on stability ball)', 
'Forearm   Pronation', 
'Cable Single Arm Triceps Pushdown (Rope Attachment)', 
'Dumbbell Press on Exercise Ball', 
'Band seated row', 
'Bodyweight Step up on Stepbox', 
'Resistance Band Leg Lift', 
'Dumbbell One arm Wrist Curl', 
'Barbell Biceps Curl (with arm blaster)', 
'Dumbbell Svend Press', 
'Dumbbell Reverse Spider Curl', 
'Dumbbell Incline Palm in Press', 
'Bycicle Twisting Crunch', 
'Cable One Arm Lateral Raise', 
'Dumbbell Tate Press', 
'Triceps Press', 
'Smith Standing Leg Calf Raise', 
'Air Twisting Crunch', 
'Cable Neutral Grip Lat Pulldown', 
'Kettlebell Single Leg Glute Bridge Pullover', 
'Single Leg Step up', 
'Cable Rear Delt Row (stirrups)', 
'Barbell Standing Overhead Triceps Extension', 
'Dumbbell Fly', 
'Dumbbell Lying on Floor Chest Press', 
'Barbell Wide Bench Press', 
'Wrist   Flexion', 
'Smith Deadlift', 
'Barbell Zercher Squat Hold', 
'Knee Touch Crunch', 
'Barbell full Zercher Squat', 
'V up', 
'Cable Standing Front Raise Variation', 
'Barbell Standing Wide Grip Biceps Curl', 
'Dumbbell Standing One Arm Curl (over incline bench)', 
'Dumbbell Arnold Press II', 
'Barbell Wide Shrug', 
'Triceps Press (Head Below Bench)', 
'Incline Scapula Push up', 
'Squat (with band)', 
'Barbell Rack Pull', 
'Kettlebell Gobelt Curtsey Lunge', 
'Band Low Chest Press', 
'Bodyweight Standing Military Press', 
'Barbell Bent Over Wide Row Plus', 
'Band One Arm Standing Wide Grip Low Row', 
'Biceps Curl with Bed Sheet', 
'Dumbbell Incline Triceps Extension', 
'Lever Seated Dip', 
'Band hammer curl', 
'Cable One Arm Wrist Curl', 
'Cable Low Row with Rope Attachment', 
'Dumbbell One Arm Wide Grip Bench Press', 
'Barbell One Leg Squat', 
'Band Upright Row (Under two feet)', 
'Dumbbell Cuban Press (version 2)', 
'Cable Standing Wrist Reverse Curl', 
'Two Legs Hammer Curl with Towel (VERSION 2)', 
'Hanging Straight Leg Raise', 
'Dumbbell Standing Biceps Curl', 
'Cable Decline Fly_1', 
'Body Up', 
'Nordic Hamstring Curl', 
'Barbell Front Raise', 
'Cable Standing Cross over High Reverse Fly', 
'Alternate Punching', 
'Dumbbell Tricep Kickback With Stork Stance', 
'Weighted Tricep Dips', 
'EZ Barbell Reverse grip Preacher Curl', 
'Cable Standing Lift', 
'Landmine Squat and Press', 
'Band Lunges', 
'Dumbbell Seated Biceps Curl to Shoulder Press', 
'One Leg Floor Calf Raise', 
'Lever Overhand Triceps Dip', 
'Cable Bent Over Row', 
'Lever Gripper Hands (plate loaded)', 
'45 degrees Back Extension', 
'Smith Hip Thrust', 
'Lever Single Leg Extension (plate loaded)', 
'Barbell Step up', 
'Hanging Oblique Knee Raise', 
'Weighted Standing Curl', 
'Isometric Chest Squeeze', 
'Hyperextension (VERSION 2)', 
'Weighted Reduction Triangle', 
'Band one arm Standing Low Row', 
'Incline Push Up Depth Jump', 
'Lever seated one leg calf raise', 
'Incline Reverse Grip Push Up', 
'Alternate Oblique Crunch', 
'Cable Standing Pulldown (with rope)', 
'Band bent', 
'Barbell Seated Calf Raise', 
'Cable Leaning Lateral Raise', 
'Crunch (straight leg up)', 
'Ring Dip', 
'Diamond Push up (on knees)', 
'Smith Squat', 
'Dumbbell Seated Calf Raise', 
'Two Legs Reverse Biceps Curl with Towel (VERSION 2)', 
'Dumbbell Over Bench Wrist Curl', 
'Chest Dip on Straight Bar', 
'45 degree back extention', 
'Weighted Counterbalanced Squat', 
'Cable pull through', 
'Kettlebell Farmers Carry', 
'Cable Seated Row (Bent bar)', 
'Cable Incline Bench Press', 
'Sled Closer Hack Squat', 
'Standing Calf Raise (On a staircase)', 
'Cable Pulldown (pro lat bar)', 
'Seated In Out Leg Raise on Floor', 
'Incline Twisting Situp', 
'Cable Bar Lateral Pulldown', 
'Dumbbell One Arm Triceps Extension (on bench)', 
'Plate Pinch', 
'Bodyweight Frog Pump', 
'Wrist   Adduction', 
'Barbell Jefferson Squat', 
'Russian Twist (with medicine ball)', 
'Single Leg Heel Touch Squat', 
'Dead Bug', 
'Bodyweight Standing Biceps Curl (VERSION 2)', 
'Hand Opposite Knee Crunch', 
'Squat side kick', 
'Wrist Circles', 
'Assisted Pistol Squat with Bed Sheet', 
'Single Leg Calf Raise (on a dumbbell)', 
'Bent over Row with Towel', 
'Cable Seated Floor One Arm Concentration Curl', 
'Dumbbell Seated Curl', 
'Cable twisting standing one arm chest press', 
'Lying Leg Raise', 
'Cable hip abduction (version 2)', 
'Resistance Band Lunge', 
'Split Squats', 
'Dumbbell Lying One Arm Press II', 
'Band upright row', 
'Sit up', 
'Cable Elevated Row', 
'Crunch (leg raise)', 
'Cable Lying Bicep Curl', 
'Suspender Abduction Lunge', 
'Lever Calf Press (plate loaded)', 
'Band Triceps Kickback', 
'Cable Kneeling Triceps Extension (VERSION 2)', 
'Lunge with Jump', 
'Brachialis Pull up', 
'Barbell Curtsey Lunge', 
'Sled Forward Angled Calf Raise', 
'Barbell Upright Row', 
'Dumbbell Incline Hammer Press', 
'Dumbbell Lying Triceps Extension', 
'Barbell Drag Curl', 
'Weighted Seated Tuck Crunch on Floor', 
'Kettlebell Lunge Pass Through', 
'Bird Dog', 
'Dumbbell Incline Biceps Curl', 
'Kettlebell One Arm Bench Press', 
'Cable Lateral Raise', 
'Barbell Thruster', 
'Cable Rope Seated Row', 
'Barbell Incline Bench Press', 
'Wrist Roller', 
'Kettlebell Plyo Pushup', 
'Dumbbell Seated Bench Extension', 
'Butt Bridge', 
'Barbell Decline Bent Arm Pullover', 
'Smith Leg Press', 
'Battling Ropes', 
'Band Assisted Muscle up_1', 
'Barbell One Arm Floor Press', 
'Dumbbell Standing Triceps Extension', 
'Cable Pulldown Bicep Curl', 
'Bodyweight Standing Row (with towel)', 
'Elbow   Extension', 
'Kettlebell deadlift', 
'Lever Biceps Curl', 
'Bridge Hip Abduction', 
'Cable Seated Face Pull (with rope)', 
'Barbell Wrist Curl II', 
'Cable Cross over Lateral Pulldown', 
'Kettlebell Lunge Clean and Press', 
'Sled 45 Leg Press', 
'Dumbbell Step up', 
'Barbell Narrow Stance Squat', 
'Frog Crunch', 
'Tuck Crunch', 
'Kettlebell Alternating Hang Clean', 
'Dumbbell Close Grip Press', 
'Dumbbell Standing One Arm Extension', 
'Cable Pushdown (straight arm) II', 
'Cable Pulldown', 
'Barbell Standing Back Wrist Curl', 
'Dumbbell Standing One Arm Curl Over Incline Bench', 
'Cable Reverse Preacher Curl', 
'Bodyweight Shrug', 
'EZ bar Drag Bicep Curl', 
'Smith Machine Decline Close Grip Bench Press', 
'Band Cross Body One Arm Chest Press', 
'Barbell Stiff Leg Good Morning', 
'Extra Decline Sit up', 
'Lever Seated Leg Extension (VERSION 2)', 
'Dumbbell Standing Zottman Preacher Curl', 
'Cable Seated Crunch', 
'Cable Rope Crossover Seated Row', 
'Barbell Curl', 
'Cable Biceps Curl (SZ bar)', 
'Dumbbell Incline Hammer Curl', 
'Dumbbell Standing Kickback', 
'Squat Hold Calf Raise', 
'Cable Parallel Grip Lat Pulldown on Floor', 
'Elbow Up and Down Dynamic Plank', 
'Side Push up', 
'Cable Seated One Arm Alternate Row', 
'EZ Barbell Standing Wrist Reverse Curl', 
'Dumbbell Incline One Arm Lateral Raise', 
'Medicine Ball Close Grip Push Up', 
'Barbell Seated Overhead Press', 
'Cable Single Arm Neutral Grip Front Raise', 
'Cable Standing Face Pull', 
'Dumbbell Hammer Curls (with arm blaster)', 
'Sliding Floor Bridge Curl on Towel', 
'Kettlebell Goblet Squat', 
'Cable Middle Fly_1', 
'Cable Front Raise', 
'Jump Squat', 
'Kettlebell Extended Range One Arm Press on Floor', 
'Circles Arm', 
'Bulgarian Split Squat with Chair', 
'Roll Seated Shoulder Flexor Depresor Retractor FIX', 
'Band Overhead Single Arm Triceps Extension', 
'Suspender Side Lunge', 
'Diamond Push up', 
'Barbell Bench Press_1', 
'Olympic Barbell Hammer Curl', 
'Dumbbell Plyo Squat', 
'Barbell Standing Close Grip Military Press', 
'Dumbbell Lying Rear Lateral Raise', 
'Cable Reverse One Arm Curl', 
'Barbell One Arm Bent over Row', 
'Dumbbell Arnold Press', 
'Barbell Incline Lying Rear Delt Raise', 
'Sissy Squat Bodyweight', 
'Kettlebell Double Alternating Hang Clean', 
'Barbell Deadstop Row', 
'Squat On Bosu Ball', 
'Cable Pushdown (with rope attachment)', 
'Bodyweight Kneeling Triceps Extension', 
'EZ Barbell Standing Preacher Curl', 
'Lever Hammer Grip Preacher Curl', 
'Barbell Seated Bradford Rocky Press', 
'Barbell Rear Lunge II', 
'Dumbbell Goblet Split Squat Front Foot Elevanted', 
'Cross Body Crunch', 
'Cable one arm twisting seated row', 
'Band pushdown', 
'Resistance Band Side Walk', 
'Suspender Arm Curl', 
'Lever Total Abdominal Crunch', 
'Band lateral raise', 
'Cable Incline Bench Row', 
'Dumbbell Side Bend', 
'Dumbbell Alternate Shoulder Press', 
'EZ Barbell JM Bench Press', 
'Barbell Reverse Wrist Curl', 
'Cable Standing Fly', 
'Barbell Incline Bench Press_1', 
'Oblique Crunches Floor', 
'EZ Barbell Close Grip Preacher Curl', 
'Side Plank m', 
'EZ Barbell Spider Curl', 
'Dumbbell Incline Triceps Extension_1', 
'Dumbbell Incline Raise', 
'Dumbbell Lateral to Front Raise', 
'Standing Single Leg Curl', 
'Barbell Clean grip Front Squat', 
'Barbell Lying Close grip Triceps Extension', 
'Bodyweight Rear Lunge', 
'Cable Rear Pulldown', 
'Dumbbell finger curls', 
'Cable Y raise', 
'Barbell Squat 2 sec Hold', 
'Front Plank', 
'Dumbbell Single Leg Split Squat', 
'Band Close Grip Biceps Curl', 
'Cable Incline Triceps Extension', 
'Walking Lunge Male', 
'Dumbbell Lying Supine Curl', 
'Cable Standing Up Straight Crossovers', 
'Dumbbell Reverse Wrist Curl', 
'Glute Ham Raise', 
'Dumbbell Walking Lunges', 
'Sumo Squat', 
'Handboard Slope Hang', 
'Dumbbell Bent Over Alternate Rear Delt Fly', 
'Barbell Pendlay Row', 
'Band underhand pulldown', 
'Groin Crunch', 
'Band Assisted Dip_1', 
'Band lying leg curl', 
'Dumbbell Single Leg Step Up', 
'Dumbbell Front Raise II', 
'Barbell Lying Triceps Extension', 
'Band Assisted Pull Up', 
'Hip Thrusts', 
'Lever Preacher Curl_1', 
'Band Pushdown', 
'Cable Lat Pulldown Full Range Of Motion', 
'Bear Plank', 
'Lever Back Extension', 
'Resistance Band Triceps Pushdown', 
'Dumbbell One Arm Hammer Preacher Curl', 
'Dumbbell Incline Front Raise', 
'Dumbbell One Arm Standing Hammer Curl', 
'Dumbbell Straight Arm Pullover', 
'Barbell Pullover Hold', 
'Band standing leg extension', 
'Barbell Narrow Row', 
'Calf Raise from Deficit with Chair Supported', 
'Dumbbell Seated Upright Alternate Squeeze Press', 
'Dumbbell 4 Ways Lateral Raise', 
'Barbell Lying Close grip Press', 
'Captains Chair Straight Leg Raise', 
'Cable Unilateral Bicep Curl', 
'Cable Triceps Pushdown (V bar attachment)', 
'Dumbbell Lying Floor Skullcrusher', 
'Dumbbell Revers grip Biceps Curl', 
'V up', 
'Cable Forward Raise', 
'Elevanted Push Up', 
'Dumbbell Incline Two Front Raise with Chest Support', 
'Dumbbell Reverse Bench Press', 
'Dumbbell High Curl', 
'Dumbbell Lying Femoral', 
'Cable Kneeling Shoulder Press', 
'Close Grip Push up', 
'Dumbbell One Arm Front Raise', 
'Bench dip on floor', 
'Dumbbell Hammer Curl II', 
'Dumbbell Lying One Arm Pronated Triceps Extension', 
'Dumbbell Lying Hammer Press (version 2)', 
'Dumbbell Biceps Curl', 
'Inverse Leg Curl (on pull up cable machine)', 
'Cable one arm inner biceps curl', 
'Cable Seated Chest Fly', 
'Bench Reverse Crunch Circle', 
'Dumbbell Preacher Curl', 
'Band front lateral raise'];