Map<String, List<String>> muscleGroups = {
  'Back': ['Lats', 'Erectors', 'Rhomboids', 'Traps'],
  'Chest': ['Chest', 'Upper Chest', 'Lower Chest'],
  'Shoulders': ['Front Delts', 'Side Delts', 'Rear Delts'],
  'Arms': ['Biceps', 'Triceps', 'Forearms', 'Brachialis'],
  'Legs': ['Quads', 'Hamstrings', 'Glutes', 'Calves', 'Adductors'],
  'Core': ['Abdominals', 'Obliques', 'Hip Flexors']
};

Map<String, String> corrections = {
  // 'Ab Wheel': null, // NO MATCH - no ab wheel / rollout exercise found in your app's list at all
  'Arnold Press (Dumbbell)': 'dumbbell_arnold_press',
  'Assisted Tricep Dips': 'assisted_triceps_dips',
  'Back Extension (Weighted Hyperextension)': 'back_extensions',
  'Barbell Full Squat': 'barbell_squat',
  'Behind the Back Bicep Wrist Curl (Barbell)': 'barbell_behind_the_back_wrist_curls',
  'Behind the Back Curl (Cable)': 'cable_behind_the_back_wrist_curls',
  'Bench Press (Barbell)': 'barbell_bench_press',
  'Bench Press (Dumbbell)': 'dumbbell_bench_press',
  'Bench Press (Smith Machine)': 'smith_machine_bench_press',
  'Bent Over One Arm Row (Dumbbell)': 'dumbbell_bent_over_bench_row',
  'Bent Over Row (Barbell)': 'barbell_bent_over_row',
  'Bent Over Row (Dumbbell)': 'dumbbell_bent_over_bench_row',
  'Bicep Curl (Barbell)': 'barbell_curl',
  'Bicep Curl (Cable)': 'cable_curl',
  'Bicep Curl (Dumbbell)': 'dumbbell_biceps_curl',
  'Bulgarian Split Squat': 'bulgarian_split_squat',
  'Cable Bar Lateral Pulldown': 'lat_pulldown',
  'Cable Crunch': 'cable_kneeling_crunch',
  'Cable Fly Crossovers': 'cable_standing_up_straight_crossovers',
  'Cable Half Kneeling External Rotation': 'cable_kneeling_external_rotation',
  'Cable One Arm Lateral Raise': 'cable_single_arm_lateral_raise',
  'Cable Overhead Single Arm Triceps Extension (Rope)': 'cable_overhead_single_arm_triceps_extension',
  'Cable Overhead Tricep Extension Straight Bar': 'cable_overhead_triceps_extension_straight_bar',
  'Cable Overhead Tricep Single Arm Triceps Extension (Rope)': 'cable_overhead_single_arm_triceps_extension',
  'Cable Pull Through': 'cable_pull_through_rope',
  'Cable Pushdown': 'cable_triceps_pushdown_straight_bar',
  'Cable Pushdown (Rope)': 'cable_triceps_pushdown_rope',
  'Cable Standing One Arm Triceps Extension': 'cable_overhead_single_arm_triceps_extension',
  'Cable Triceps Pushdown (SZ bar)': 'cable_triceps_pushdown_ez_bar',
  'Cable Unilateral Bicep Curl': 'bayesian_curl',
  'Cable Wrist Curl (Single)': 'cable_single_arm_wrist_curl',
  'Calf Press (Machine)': 'lever_calf_press', // UNSURE - could also be 'sled_calf_press_on_leg_press'; weights (40-120kg) fit either
  'Chest Dip': 'chest_dip',
  'Chest Fly': 'machine_chest_fly',
  'Chest Fly (Dumbbell)': 'dumbbell_fly',
  'Chest Fly (Machine)': 'machine_chest_fly',
  'Chest Press (Machine)': 'lever_chest_press',
  'Chest Supported Incline Row (Dumbbell)': 'dumbbell_incline_chest_supported_row',
  'Chest Supported T Bar Row': 'lying_t_bar_row', // UNSURE - could also be 'barbell_seal_row' (both are chest-supported T-bar variants)
  'Chin Up': 'chin_up',
  'Chin Up (Weighted)': 'weighted_chin_up',
  'Concentration Curl': 'dumbbell_concentration_curl',
  'Concentration Curl (Dumbbell)': 'dumbbell_concentration_curl',
  'Cross Body Hammer Curl': 'dumbbell_cross_body_hammer_curl',
  'Crunch': 'crunch',
  'Crunch (Machine)': 'lever_seated_crunch',
  'Dead Hang': 'dead_hang',
  'Deadlift (Barbell)': 'barbell_deadlift',
  'Decline Crunch (Weighted)': 'weighted_decline_crunch',
  'EZ Bar Biceps Curl': 'ez_barbell_curl',
  'Face Pull': 'cable_standing_rope_face_pull',
  'Farmers Walk': 'farmer_walk',
  'Flat Leg Raise': 'seated_leg_raise',
  'flutter kicks': 'seated_flutter_kick',
  'Flutter kicks': 'seated_flutter_kick',
  // 'Forearm': null, // NO MATCH - too generic; app has many specific forearm/wrist-curl variants, pick manually
  'Front Raise (Cable)': 'cable_front_raise',
  'Front Raise (Dumbbell)': 'dumbbell_front_raise',
  'Hack Squat': 'barbell_hack_squat',
  'Hack Squat (Machine)': 'hack_squat',
  'Hammer Curl (Cable)': 'cable_rope_hammer_curl',
  'Hammer Curl (Dumbbell)': 'dumbbell_hammer_curl',
  'Hip Abduction (Machine)': 'machine_hip_abductor',
  'Hip Abductor (Machine)': 'machine_hip_abductor',
  'Hip Adduction (Machine)': 'machine_hip_adduction',
  'Hip Thrust (Barbell)': 'barbell_hip_thrust',
  'Hip Thrust (Machine)': 'lever_hip_thrust',
  'Incline Bench Press (Barbell)': 'barbell_incline_bench_press',
  'Incline Bench Press (Dumbbell)': 'dumbbell_incline_bench_press',
  'Incline Bench Press (Smith Machine)': 'smith_machine_incline_bench_press',
  'Incline Chest Press (Machine)': 'lever_incline_chest_press',
  'Iso-Lateral Chest Press (Machine)': 'lever_chest_press_plate_loaded',
  'Iso-Lateral Row (Machine)': 'seated_lever_machine_row',
  'JM Press (Barbell)': 'barbell_jm_bench_press',
  'Jumping Jack': 'jumping_jack',
  'Lat Pulldown (Cable)': 'lat_pulldown',
  'Lat Pulldown (Machine)': 'machine_lat_pulldown',
  'Lat Pulldown - Close Grip (Cable)': 'cable_close_grip_lat_pulldown',
  'Lateral Raise (Cable)': 'cable_single_arm_lateral_raise',
  'Lateral Raise (Dumbbell)': 'dumbbell_standing_lateral_raise',
  // 'Lateral Raise (Machine)': null, // NO MATCH - no machine/lever lateral raise slug exists in your app list (only cable/dumbbell variants)
  'Leg Extension (Machine)': 'lever_leg_extension',
  'Leg Press': 'sled_leg_press',
  'Leg Press (Machine)': 'sled_leg_press',
  'Leg Press Horizontal (Machine)': 'lever_seated_leg_press',
  'Leg Raise Parallel Bars': 'captain_seat_leg_raise',
  'lever Row': 'seated_lever_machine_row',
  'Low Cable Fly Crossovers': 'cable_low_fly',
  'Lying Leg Curl (Machine)': 'lever_lying_leg_curl',
  // 'Negative Pull Up': null, // NO MATCH - no eccentric/negative-specific pull-up variant in app; closest generic is 'pull_up'
  'Overhead Press (Barbell)': 'barbell_standing_overhead_press',
  'Overhead Triceps Extension (Cable)': 'cable_overhead_triceps_extension_rope',
  'Plank': 'plank',
  'Preacher Curl (Barbell)': 'barbell_preacher_curl',
  'Preacher Curl (Dumbbell)': 'dumbbell_preacher_curl',
  'Preacher Curl (Machine)': 'lever_preacher_curl',
  'Pull Up': 'pull_up',
  'Pull Up (Assisted)': 'assisted_pull_up',
  'Pull Up (Weighted)': 'weighted_pull_up',
  'Pullover (Dumbbell)': 'dumbbell_pullover',
  'Push Up': 'push_up',
  'Rear Delt Reverse Fly (Cable)': 'standing_two_arm_cable_rear_delt_fly',
  'Rear Delt Reverse Fly (Dumbbell)': 'dumbbell_rear_delt_raise',
  'Rear Delt Reverse Fly (Machine)': 'rear_delt_fly_machine',
  'Reverse Curl (Barbell)': 'barbell_reverse_curl',
  'Reverse Curl (Dumbbell)': 'dumbbell_biceps_curl_reverse_grip',
  'Reverse Fly (Machine)': 'rear_delt_fly_machine',
  'Reverse Grip Concentration Curl (Dumbbell)': 'dumbbell_seated_reverse_concentration_curl',
  'Reverse Wrist Curls (Extensors)': 'dumbbell_reverse_wrist_curl', // UNSURE - light weights (5-7.5kg) suggest dumbbell over 'barbell_reverse_wrist_curl'
  'Romanian Deadlift (Barbell)': 'barbell_romanian_deadlift',
  'Rope Straight Arm Pulldown': 'lat_pullover_rope',
  'Running': 'running',
  'scissors': 'scissors_advanced',
  'Seated Cable Row - Bar Grip': 'cable_low_seated_row',
  'Seated Cable Row - Bar Wide Grip': 'wide_grip_overhand_row',
  'Seated Cable Row - V Grip (Cable)': 'cable_seated_row',
  'Seated Calf Raise': 'lever_seated_calf_raise',
  'Seated Calf Raise (Plate Loaded)': 'lever_seated_calf_raise',
  'Seated Dip Machine': 'lever_seated_dip',
  'Seated Incline Curl (Dumbbell)': 'dumbbell_incline_biceps_curl',
  'Seated Leg Curl (Machine)': 'lever_seated_leg_curl',
  'Seated Leg Press (Machine)': 'lever_seated_leg_press',
  'Seated Palms Up Wrist Curl': 'dumbbell_seated_palms_up_flexors_wrist_curl',
  'Seated Palms Up Wrist Curl (Dumbbell)': 'dumbbell_seated_palms_up_flexors_wrist_curl',
  'Seated Row (Cable)': 'cable_seated_row',
  'Seated Row (Machine)': 'seated_lever_machine_row',
  'Seated Shoulder Press (Machine)': 'lever_seated_shoulder_press',
  'Shoulder Press (Dumbbell)': 'dumbbell_seated_shoulder_press',
  'Shoulder Press (Machine Plates)': 'machine_shoulder_press',
  'Shrug (Dumbbell)': 'dumbbell_shrug',
  'Side Bend': 'side_bend',
  'Side Bend (Dumbbell)': 'dumbbell_side_bend',
  'Side Plank': 'side_plank',
  'Single Arm Cable Row': 'cable_one_arm_row',
  'Single Arm Curl (Cable)': 'cable_one_arm_biceps_curl',
  'Single Arm Lateral Raise (Cable)': 'cable_single_arm_lateral_raise',
  'Single Arm Tricep Extension (Dumbbell)': 'dumbbell_seated_one_arm_triceps_extension',
  'Single Arm Triceps Extension (Dumbbell)': 'dumbbell_seated_one_arm_triceps_extension',
  'Single Arm Triceps Pushdown (Cable)': 'cable_one_arm_triceps_pushdown',
  'Single Leg Standing Calf Raise (Dumbbell)': 'dumbbell_standing_single_leg_calf_raise',
  'Sissy Squat (Weighted)': 'weighted_sissy_squat',
  'Sit Up': 'sit_up',
  'Skullcrusher (Barbell)': 'barbell_lying_triceps_extension_skull_crusher',
  'Skullcrusher (Dumbbell)': 'dumbbell_lying_floor_skullcrusher',
  'Sled Hack Squat': 'hack_squat',
  'Squat (Barbell)': 'barbell_squat',
  'Stair Machine': 'stair_master',
  // 'Standing Calf Raise': null, // UNSURE/NO MATCH - your logged sets are bodyweight (no weight, 20 reps), but every "standing calf raise" slug in your app implies equipment (lever_/barbell_/dumbbell_/smith_ standing_calf_raise)
  'Standing Calf Raise (Machine)': 'lever_standing_calf_raise',
  'Standing Calf Raise (Smith)': 'smith_calf_raise',
  'Straight Arm Lat Pulldown (Cable)': 'cable_pullover',
  'T Bar Row': 'lying_t_bar_row',
  // 'Treadmill': null, // UNSURE - distance/duration logged (2.64km/30min) suggests a walk or slow jog; app has no treadmill-specific slug, only 'running' and 'walking' - pick based on your actual pace
  'Triceps Dip': 'triceps_dips',
  'Triceps Dip (Assisted)': 'assisted_triceps_dips',
  'Triceps Dip (Weighted)': 'weighted_triceps_dips',
  'Triceps Extension (Barbell)': 'barbell_standing_overhead_triceps_extension',
  'Triceps Extension (Cable)': 'cable_overhead_single_arm_triceps_extension',
  'Triceps Extension (Dumbbell)': 'dumbbell_seated_triceps_extension',
  'Triceps Pushdown': 'cable_triceps_pushdown_straight_bar',
  'Triceps Rope Pushdown': 'cable_triceps_pushdown_rope',
  'Vertical Leg Raise (on parallel bars)': 'captain_seat_leg_raise',
  'Walking': 'walking',
  'Wrist Curl (Flexors)': 'barbell_wrist_curl', // UNSURE - could also be 'cable_wrist_curl'; weight pattern (21.25kg, .25 increments) is ambiguous between barbell and cable stack
  'Wrist Curl Cable': 'cable_standing_flexors_wrist_curl',
  'Zottman Curl (Dumbbell)': 'dumbbell_zottman_curl',
  'Archer Pull Up': 'archer_pull_up',
  'Assisted Chest Dips': 'assisted_chest_dips',
  'Assisted Neutral Grip Pull Ups': 'assisted_neutral_grip_pull_ups',
  'Assisted Pull Up': 'assisted_pull_up',
  'Assisted Triceps Dips': 'assisted_triceps_dips',
  'Back Extensions': 'back_extensions',
  'Band Assisted Dips': 'band_assisted_dips',
  'Band face pull': 'band_face_pull',
  'Barbell Bench Press': 'barbell_bench_press',
  'Barbell Curl': 'barbell_curl',
  'Barbell Deadlift': 'barbell_deadlift',
  'Barbell Incline Bench Press': 'barbell_incline_bench_press',
  'Barbell JM Bench Press': 'barbell_jm_bench_press',
  'Barbell Lying Triceps Extension Skull Crusher': 'barbell_lying_triceps_extension_skull_crusher',
  'Barbell Preacher Curl': 'barbell_preacher_curl',
  'Barbell Squat': 'barbell_squat',
  'Bayesian Curl': 'bayesian_curl',
  'Cable Behind the Back Wrist Curls': 'cable_behind_the_back_wrist_curls',
  'Cable Cross over Lateral Pulldown': 'cable_cross_over_lateral_pulldown',
  'Cable Curl': 'cable_curl',
  'Cable High Pulley Overhead Tricep Extension': 'cable_high_pulley_overhead_triceps_extension',
  'Cable Kneeling Crunch': 'cable_kneeling_crunch',
  'Cable Kneeling External Rotation': 'cable_kneeling_external_rotation',
  'Cable Low Seated Row': 'cable_low_seated_row',
  'Cable Neutral Grip Lat Pulldown': 'cable_neutral_grip_lat_pulldown',
  'Cable One Arm Biceps Curl': 'cable_one_arm_biceps_curl',
  'Cable One Arm Row': 'cable_one_arm_row',
  'Cable One Arm Triceps Pushdown': 'cable_one_arm_triceps_pushdown',
  'Cable Overhead Single Arm Triceps Extension': 'cable_overhead_single_arm_triceps_extension',
  'Cable Overhead Triceps Extension (Rope)': 'cable_overhead_triceps_extension_rope',
  'Cable Overhead Triceps Extension (Rope) (edge)': 'cable_overhead_triceps_extension_rope',
  'Cable Overhead Triceps Extension (Straight Bar)': 'cable_overhead_triceps_extension_straight_bar',
  'Cable Pullover': 'cable_pullover',
  'Cable Rope High Pulley Overhead Tricep Extension': 'cable_high_pulley_overhead_triceps_extension',
  'Cable Seated Chest Fly': 'cable_seated_chest_fly',
  'Cable Seated High Row (V bar)': 'cable_seated_high_row_v_bar',
  'Cable Seated One Arm Concentration Curl': 'cable_seated_one_arm_concentration_curl',
  'Cable Seated Pullover': 'cable_seated_pullover',
  'Cable Seated Row (Bent bar)': 'cable_seated_row_bent_bar',
  'Cable Seated Shoulder Internal Rotation': 'cable_seated_shoulder_internal_rotation',
  'Cable Single Arm Lateral Raise': 'cable_single_arm_lateral_raise',
  'Cable Standing Face Pull (Rope)': 'cable_standing_rope_face_pull',
  'Cable Triceps Pushdown (EZ bar)': 'cable_triceps_pushdown_ez_bar',
  'Cable Triceps Pushdown (Rope)': 'cable_triceps_pushdown_rope',
  'Cable Triceps Pushdown (Straight Bar)': 'cable_triceps_pushdown_straight_bar',
  'Cable Y raise': 'cable_y_raise',
  'Cable seated row': 'cable_seated_row',
  'Captain Seat Leg Raise': 'captain_seat_leg_raise',
  'Chest Dips': 'chest_dip',
  'Dumbbell Bench Press': 'dumbbell_bench_press',
  'Dumbbell Bent Over Bench Row': 'dumbbell_bent_over_bench_row',
  'Dumbbell Biceps Curl': 'dumbbell_biceps_curl',
  'Dumbbell Biceps Curls supported': 'dumbbell_seated_curl',
  'Dumbbell Concentration Curl': 'dumbbell_concentration_curl',
  'Dumbbell Hammer Curl': 'dumbbell_hammer_curl',
  'Dumbbell Incline Bench Press': 'dumbbell_incline_bench_press',
  'Dumbbell Incline Single Arm Lateral Raise': 'dumbbell_incline_single_arm_lateral_raise',
  'Dumbbell Incline Y Raise': 'dumbbell_incline_y_raise',
  'Dumbbell Lateral Raise': 'dumbbell_standing_lateral_raise',
  'Dumbbell Over Bench Neutral Wrist Curl': 'dumbbell_over_bench_neutral_wrist_curl',
  'Dumbbell Over Bench Wrist Curl': 'dumbbell_over_bench_wrist_curl',
  'Dumbbell Preacher Curl': 'dumbbell_preacher_curl',
  'Dumbbell Seated Bicep Curl': 'dumbbell_seated_curl',
  'Dumbbell Seated Shoulder Press': 'dumbbell_seated_shoulder_press',
  'Dumbbell Single Arm Preacher Curl': 'dumbbell_single_arm_preacher_curl',
  'EZ Barbell Close Grip Preacher Curl': 'ez_barbell_close_grip_preacher_curl',
  'EZ Barbell Curl': 'ez_barbell_curl',
  // 'Explosive pull up': null,
  'Finger Curls': 'finger_curls',
  'Lat Pulldown': 'lat_pulldown',
  'Lever Biceps Curl': 'lever_biceps_curl',
  'Lever Chest Press': 'lever_chest_press',
  'Lever Hammer Grip Preacher Curl': 'lever_hammer_grip_preacher_curl',
  'Lever Leg Extension': 'lever_leg_extension',
  'Lever Lying Leg Curl': 'lever_lying_leg_curl',
  'Lever Seated Dip': 'lever_seated_dip',
  'Lever Seated Hip Adduction': 'lever_seated_hip_adduction',
  'Lever Seated Leg Curl': 'lever_seated_leg_curl',
  'Lever Standing Calf Raise': 'lever_standing_calf_raise',
  'Lever Triceps Extension': 'lever_triceps_extension',
  'Lying Leg Raise': 'lying_leg_raise',
  'Lying T-Bar Row': 'lying_t_bar_row',
  'Machine Chest Fly': 'machine_chest_fly',
  'Machine Hip Abductor': 'machine_hip_abductor',
  'Machine Lat Pulldowns': 'machine_lat_pulldown',
  'Machine Shoulder Press': 'machine_shoulder_press',
  // 'Negative dips': null,
  'Neutral Grip Pull Up': 'neutral_grip_pull_up',
  'Rear Delt Fly (Machine)': 'rear_delt_fly_machine',
  'Seated Lever Machine Row': 'seated_lever_machine_row',
  'Seated Machine Row': 'seated_machine_row',
  'Seated Overhead Press (Barbell)': 'seated_overhead_press_barbell',
  'Sit up': 'sit_up',
  'Smith Calf Raise': 'smith_calf_raise',
  'Stair Master': 'stair_master',
  'Standing Overhead Press (Barbell)': 'barbell_standing_overhead_press',
  'Standing Single Arm Cable Rear Delt Fly': 'standing_single_arm_cable_rear_delt_fly',
  'Standing Two Arm Cable Rear Delt Fly': 'standing_two_arm_cable_rear_delt_fly',
  // 'Zercher Squat': null,
};