Map<String, List<String>> muscleGroups = {
  'Back': ['Lats', 'Erectors', 'Rhomboids', 'Traps'],
  'Chest': ['Chest', 'Upper Chest', 'Lower Chest'],
  'Shoulders': ['Front Delts', 'Side Delts', 'Rear Delts'],
  'Arms': ['Biceps', 'Triceps', 'Forearms', 'Brachialis'],
  'Legs': ['Quads', 'Hamstrings', 'Glutes', 'Calves', 'Adductors'],
  'Core': ['Abdominals', 'Obliques', 'Hip Flexors']
};

Map<String, String> corrections = {
  'Pull Up (Weighted)': 'Weighted Pull Up',
  'Iso-Lateral Row (Machine)': 'Seated Lever Machine Row',
  'Straight Arm Lat Pulldown (Cable)': 'Cable Pullover',
  'Seated Cable Row - V Grip (Cable)': 'Cable seated row',
  'Single Arm Curl (Cable)': 'Cable One Arm Biceps Curl',
  'Bench Press (Barbell)': 'Barbell Bench Press',
  'Triceps Dip (Weighted)': 'Weighted Triceps Dips',
  'Lateral Raise (Cable)': 'Cable Single Arm Lateral Raise',
  'Triceps Rope Pushdown': 'Cable Triceps Pushdown (Rope)',
  'Incline Bench Press (Dumbbell)': 'Dumbbell Incline Bench Press',
  'Cable Wrist Curl (Single)': 'Cable Single Arm Wrist Curl',
  'Seated Palms Up Wrist Curl': 'Dumbbell Seated Palms Up Wrist Curl',
  'Bent Over Row (Barbell)': 'Barbell Bent Over Row',
  'Bench Press (Dumbbell)': 'Dumbbell Bench Press',
  'Bicep Curl (Dumbbell)': 'Dumbbell Biceps Curl',
  'Triceps Dip': 'Triceps Dips',
  'Triceps Extension (Cable)': 'Cable Overhead Single Arm Triceps Extension',
  'T Bar Row': 'Lying T-Bar Row',
  'Lat Pulldown (Machine)': 'Machine Lat Pulldowns',
  'Lateral Raise (Dumbbell)': 'Dumbbell Lateral Raise',
  'Standing Calf Raise (Smith)': 'Smith Calf Raise',
  'Hip Thrust (Barbell)': 'Barbell Hip Thrust',
  'Leg Extension (Machine)': 'Lever Leg Extension',
  'Deadlift (Barbell)': 'Barbell Deadlift',
  'Back Extension (Weighted Hyperextension)': 'Back Extensions',
  'Incline Bench Press (Barbell)': 'Barbell Incline Bench Press',
  'Chin Up': 'Chin Up',
  'Overhead Press (Barbell)': 'Standing Overhead Press (Barbell)',
  'Bicep Curl (Cable)': 'Cable Curl',
  'Bicep Curl (Barbell)': 'Barbell Curl',
  'Chest Fly (Machine)': 'Machine Chest Fly',
  'Pull Up': 'Pull Up',
  'Rear Delt Reverse Fly (Machine)': 'Rear Delt Fly (Machine)',
  'Hammer Curl (Dumbbell)': 'Dumbbell Hammer Curl',
  'Leg Press (Machine)': 'Sled Leg Press',
  'Shoulder Press (Dumbbell)': 'Dumbbell Seated Shoulder Press',
  'Cable Pull Through': 'Cable Pull Through (Rope)',
  'Cable Fly Crossovers': 'Cable Standing Up Straight Crossovers',
  'Preacher Curl (Barbell)': 'Barbell Preacher Curl',
  'Single Arm Lateral Raise (Cable)': 'Cable Single Arm Lateral Raise',
  'Hammer Curl (Cable)': 'Cable Hammer Curl (Rope)',
  'Dead Hang': 'Dead Hang',
  'Seated Cable Row - Bar Grip': 'Cable Low Seated Row',
  'Seated Cable Row - Bar Wide Grip': 'Wide Grip Overhand Row',
  'Single Arm Cable Row': 'Cable One Arm Row',
  'Lat Pulldown (Cable)': 'Lat Pulldown',
  'Leg Raise Parallel Bars': 'Captain Seat Leg Raise',
  'Hack Squat (Machine)': 'Hack Squat',
  'Hack Squat': 'Barbell Hack Squat',
  'Farmers Walk': 'Farmer Walk',
  'Incline Bench Press (Smith Machine)': 'Smith Machine Incline Bench Press',
  'Chin Up (Weighted)': 'Weighted Chin Up',
  'Low Cable Fly Crossovers': 'Low Cable Fly',
  'Behind the Back Bicep Wrist Curl (Barbell)': 'Barbell Behind the Back Wrist Curls',
  'Push Up': 'Push Up',
  'Flat Leg Raise': 'Seated Leg Raise',
  'Sit Up': 'Sit Up',
  'Concentration Curl (Dumbbell)': 'Dumbbell Concentration Curl',
  'Front Raise (Dumbbell)': 'Dumbbell Front Raise',
//   'Shoulder Press (Machine)': 'Lever Seated Shoulder Press',
  'Chest Dip': 'Chest Dip',
  'Seated Incline Curl (Dumbbell)': 'Dumbbell Incline Biceps Curl',
  'Chest Fly': 'Machine Chest Fly',
  'Seated Row (Cable)': 'Cable seated row',
  'Triceps Extension (Dumbbell)': 'Dumbbell Seated Triceps Extension',
  'Triceps Dip (Assisted)': 'Assisted Triceps Dips',
  'Reverse Curl (Barbell)': 'Barbell Reverse Curl',
  'Seated Calf Raise (Plate Loaded)': 'Lever Seated Calf Raise',
  'Leg Press': 'Sled Leg Press',
  'Reverse Fly (Machine)': 'Rear Delt Fly (Machine)',
  'Bulgarian Split Squat': 'Bulgarian Split Squat',
  'Seated Leg Press (Machine)': 'Lever Seated Leg Press',
  'Seated Leg Curl (Machine)': 'Lever Seated Leg Curl',
  'Preacher Curl (Machine)': 'Lever Preacher Curl',
  'Seated Palms Up Wrist Curl (Dumbbell)': 'Dumbbell Seated Palms Up Wrist Curl',
  'flutter kicks': 'Seated Flutter Kick',
  'scissors': 'Scissors (advanced)',
  'Flutter kicks': 'Seated Flutter Kick',
  'Bent Over One Arm Row (Dumbbell)': 'Dumbbell Bent Over Bench Row',
  'Bent Over Row (Dumbbell)': 'Dumbbell Bent Over Bench Row',
  'Skullcrusher (Dumbbell)': 'Dumbbell Lying Floor Skullcrusher',
  'Pullover (Dumbbell)': 'Dumbbell Pullover',
  'Reverse Curl (Dumbbell)': 'Dumbbell Biceps Curl Reverse Grip',
  'lever Row': 'Seated Lever Machine Row', // !
  'Triceps Extension (Barbell)': 'Barbell Standing Overhead Triceps Extension',
  'Skullcrusher (Barbell)': 'Barbell Lying Triceps Extension Skull Crusher',
  'Plank': 'Plank',
  'Jumping Jack': 'Jumping Jack',
  'Crunch': 'Crunch',
  'Running': 'Running',
  'Reverse Grip Concentration Curl (Dumbbell)': 'Dumbbell Seated Reverse Concentration Curl',
  'Arnold Press (Dumbbell)': 'Dumbbell Arnold Press',
  'Walking': 'Walking',
  'Pull Up (Assisted)': 'Assisted Pull Up',
  'Iso-Lateral Chest Press (Machine)': 'Lever Chest Press (plate loaded)',
  'Incline Chest Press (Machine)': 'Incline Lever Chest Press',
  'Hip Abductor (Machine)': 'Machine Hip Abductor',
  'Side Plank': 'Side Plank',
  'Triceps Pushdown': 'Cable Triceps Pushdown (Straight Bar)',
  'Single Arm Triceps Pushdown (Cable)': 'Cable One Arm Triceps Pushdown',
  'Squat (Barbell)': 'Barbell Squat',
  'Chest Press (Machine)': 'Lever Chest Press',
  'Seated Calf Raise': 'Lever Seated Calf Raise',
  'Hip Thrust (Machine)': 'Lever Hip Thrust',
  'Zottman Curl (Dumbbell)': 'Dumbbell Zottman Curl',
  'Sissy Squat (Weighted)': 'Weighted Sissy Squat',
  'Seated Shoulder Press (Machine)': 'Lever Seated Shoulder Press',
  'Shoulder Press (Machine Plates)': 'Machine Shoulder Press',
  'Chest Supported Incline Row (Dumbbell)': 'Dumbbell Incline Chest Supported Row',
  'Lying Leg Curl (Machine)': 'Lever Lying Leg Curl',
  'Cross Body Hammer Curl': 'Dumbbell Cross Body Hammer Curl',
  'Single Leg Standing Calf Raise (Dumbbell)': 'Dumbbell Standing Single Leg Calf Raise',
  'Single Arm Triceps Extension (Dumbbell)': 'Dumbbell Seated One Arm Triceps Extension',
  'Face Pull': 'Cable Standing Face Pull (Rope)',
  'Lat Pulldown - Close Grip (Cable)': 'Cable Close Grip Lat Pulldown',
  'Seated Row (Machine)': 'Seated Lever Machine Row',
  'Rear Delt Reverse Fly (Dumbbell)': 'Dumbbell Rear Delt Fly',
  'Stair Machine': 'Stair Master',
  'Chest Fly (Dumbbell)': 'Dumbbell Fly',
  'Cable Crunch': 'Cable Kneeling Crunch',
  'Wrist Curl Cable': 'Cable Standing Wrist Curl',
  'Bench Press (Smith Machine)': 'Smith Machine Bench Press',
  'Decline Crunch (Weighted)': 'Weighted Decline Crunch',
  'Seated Dip Machine': 'Lever Seated Dip',
  'Shrug (Dumbbell)': 'Dumbbell Shrug',
  'Cable Pushdown (Rope)': 'Cable Triceps Pushdown (Rope)',
  'Preacher Curl (Dumbbell)': 'Dumbbell Preacher Curl',
  'Rear Delt Reverse Fly (Cable)': 'Standing Two Arm Cable Rear Delt Fly',
  'JM Press (Barbell)': 'Barbell JM Bench Press',
  'Behind the Back Curl (Cable)': 'Cable Behind the Back Wrist Curls',
  'Hip Adduction (Machine)': 'Machine Hip Adduction',
  'Front Raise (Cable)': 'Cable Front Raise',
  'Side Bend (Dumbbell)': 'Dumbbell Side Bend',
  'Side Bend': 'Side Bend',
  'Rope Straight Arm Pulldown': 'Lat Pullover (Rope)',
  'Crunch (Machine)': 'Lever Seated Crunch',
  'Standing Calf Raise (Machine)': 'Lever Standing Calf Raise',
  'Single Arm Tricep Extension (Dumbbell)': 'Dumbbell Seated One Arm Triceps Extension',
  'Leg Press Horizontal (Machine)': 'Lever Seated Leg Press',
  'Overhead Triceps Extension (Cable)': 'Cable Overhead Triceps Extension (Rope)',
  'Concentration Curl': 'Dumbbell Concentration Curl',


  // ! Moving from renamed exercises section
  'Cable One Arm Lateral Raise': 'Cable Single Arm Lateral Raise',
  'Cable Half Kneeling External Rotation': 'Cable Kneeling External Rotation',
  'Assisted Tricep Dips': 'Assisted Triceps Dips',
  'Cable Pushdown': 'Cable Triceps Pushdown (Straight Bar)',
  'Cable Unilateral Bicep Curl': 'Bayesian Curl',
  'Sled Hack Squat': 'Hack Squat',
  'Cable Triceps Pushdown (SZ bar)': 'Cable Triceps Pushdown (EZ bar)',
  'Barbell Full Squat': 'Barbell Squat',
  'Cable Standing One Arm Triceps Extension': 'Cable Overhead Single Arm Triceps Extension',
  'Cable Overhead Tricep Extension Straight Bar': 'Cable Overhead Triceps Extension (Straight Bar)',
  'Vertical Leg Raise (on parallel bars)': 'Captain Seat Leg Raise',
  'Cable Overhead Tricep Single Arm Triceps Extension (Rope)': 'Cable Overhead Single Arm Triceps Extension',
  'Cable Overhead Single Arm Triceps Extension (Rope)': 'Cable Overhead Single Arm Triceps Extension',
  'Cable Bar Lateral Pulldown': 'Lateral Pulldown',
};

final Map<String, String?> exerciseConversionMap = {
  'Archer Pull Up': 'archer_pull_up',
  'Assisted Chest Dips': 'assisted_chest_dips',
  'Assisted Neutral Grip Pull Ups': 'assisted_neutral_grip_pull_ups',
  'Assisted Pull Up': 'assisted_pull_up',
  'Assisted Triceps Dips': 'assisted_triceps_dips',
  'Back Extensions': 'back_extensions',
  'Band Assisted Dips': 'band_assisted_dips',
  'Band face pull': 'band_face_pull',
  'Barbell Bench Press': 'barbell_bench_press',
  'Barbell Curl': 'barbell_curl',
  'Barbell Deadlift': 'barbell_deadlift',
  'Barbell Incline Bench Press': 'barbell_incline_bench_press',
  'Barbell JM Bench Press': 'barbell_jm_bench_press',
  'Barbell Lying Triceps Extension Skull Crusher': 'barbell_lying_triceps_extension_skull_crusher',
  'Barbell Preacher Curl': 'barbell_preacher_curl',
  'Barbell Squat': 'barbell_squat',
  'Bayesian Curl': 'bayesian_curl',
  'Cable Behind the Back Wrist Curls': 'cable_behind_the_back_wrist_curls',
  'Cable Cross over Lateral Pulldown': 'cable_cross_over_lateral_pulldown',
  'Cable Curl': 'cable_curl',
  'Cable High Pulley Overhead Tricep Extension': 'cable_high_pulley_overhead_triceps_extension',
  'Cable Kneeling Crunch': 'cable_kneeling_crunch',
  'Cable Kneeling External Rotation': 'cable_kneeling_external_rotation',
  'Cable Low Seated Row': 'cable_low_seated_row',
  'Cable Neutral Grip Lat Pulldown': 'cable_neutral_grip_lat_pulldown',
  'Cable One Arm Biceps Curl': 'cable_one_arm_biceps_curl',
  'Cable One Arm Row': 'cable_one_arm_row',
  'Cable One Arm Triceps Pushdown': 'cable_one_arm_triceps_pushdown',
  'Cable Overhead Single Arm Triceps Extension': 'cable_overhead_single_arm_triceps_extension',
  'Cable Overhead Triceps Extension (Rope)': 'cable_overhead_triceps_extension_rope',
  'Cable Overhead Triceps Extension (Rope) (edge)': 'cable_overhead_triceps_extension_rope',
  'Cable Overhead Triceps Extension (Straight Bar)': 'cable_overhead_triceps_extension_straight_bar',
  'Cable Pullover': 'cable_pullover',
  'Cable Pushdown (Rope)': 'cable_triceps_pushdown_rope',
  'Cable Rope High Pulley Overhead Tricep Extension': 'cable_high_pulley_overhead_triceps_extension',
  'Cable Seated Chest Fly': 'cable_seated_chest_fly',
  'Cable Seated High Row (V bar)': 'cable_seated_high_row_v_bar',
  'Cable Seated One Arm Concentration Curl': 'cable_seated_one_arm_concentration_curl',
  'Cable Seated Pullover': 'cable_seated_pullover',
  'Cable Seated Row (Bent bar)': 'cable_seated_row_bent_bar',
  'Cable Seated Shoulder Internal Rotation': 'cable_seated_shoulder_internal_rotation',
  'Cable Single Arm Lateral Raise': 'cable_single_arm_lateral_raise',
  'Cable Standing Face Pull (Rope)': 'cable_standing_rope_face_pull',
  'Cable Triceps Pushdown (EZ bar)': 'cable_triceps_pushdown_ez_bar',
  'Cable Triceps Pushdown (Rope)': 'cable_triceps_pushdown_rope',
  'Cable Triceps Pushdown (Straight Bar)': 'cable_triceps_pushdown_straight_bar',
  'Cable Y raise': 'cable_y_raise',
  'Cable seated row': 'cable_seated_row',
  'Captain Seat Leg Raise': 'captain_seat_leg_raise',
  'Chest Dips': 'chest_dip',
  'Dumbbell Bench Press': 'dumbbell_bench_press',
  'Dumbbell Bent Over Bench Row': 'dumbbell_bent_over_bench_row',
  'Dumbbell Biceps Curl': 'dumbbell_biceps_curl',
  'Dumbbell Biceps Curls supported': 'dumbbell_seated_curl',
  'Dumbbell Concentration Curl': 'dumbbell_concentration_curl',
  'Dumbbell Hammer Curl': 'dumbbell_hammer_curl',
  'Dumbbell Incline Bench Press': 'dumbbell_incline_bench_press',
  'Dumbbell Incline Single Arm Lateral Raise': 'dumbbell_incline_single_arm_lateral_raise',
  'Dumbbell Incline Y Raise': 'dumbbell_incline_y_raise',
  'Dumbbell Lateral Raise': 'dumbbell_standing_lateral_raise',
  'Dumbbell Over Bench Neutral Wrist Curl': 'dumbbell_over_bench_neutral_wrist_curl',
  'Dumbbell Over Bench Wrist Curl': 'dumbbell_over_bench_wrist_curl',
  'Dumbbell Preacher Curl': 'dumbbell_preacher_curl',
  'Dumbbell Seated Bicep Curl': 'dumbbell_seated_curl',
  'Dumbbell Seated Shoulder Press': 'dumbbell_seated_shoulder_press',
  'Dumbbell Single Arm Preacher Curl': 'dumbbell_single_arm_preacher_curl',
  'EZ Barbell Close Grip Preacher Curl': 'ez_barbell_close_grip_preacher_curl',
  'EZ Barbell Curl': 'ez_barbell_curl',
  'Explosive pull up': null,
  'Finger Curls': 'finger_curls',
  'Hack Squat': 'hack_squat',
  'Lat Pulldown': 'lat_pulldown',
  'Lever Biceps Curl': 'lever_biceps_curl',
  'Lever Chest Press': 'lever_chest_press',
  'Lever Hammer Grip Preacher Curl': 'lever_hammer_grip_preacher_curl',
  'Lever Leg Extension': 'lever_leg_extension',
  'Lever Lying Leg Curl': 'lever_lying_leg_curl',
  'Lever Seated Dip': 'lever_seated_dip',
  'Lever Seated Hip Adduction': 'lever_seated_hip_adduction',
  'Lever Seated Leg Curl': 'lever_seated_leg_curl',
  'Lever Standing Calf Raise': 'lever_standing_calf_raise',
  'Lever Triceps Extension': 'lever_triceps_extension',
  'Lying Leg Raise': 'lying_leg_raise',
  'Lying T-Bar Row': 'lying_t_bar_row',
  'Machine Chest Fly': 'machine_chest_fly',
  'Machine Hip Abductor': 'machine_hip_abductor',
  'Machine Lat Pulldowns': 'machine_lat_pulldown',
  'Machine Shoulder Press': 'machine_shoulder_press',
  'Negative dips': null,
  'Neutral Grip Pull Up': 'neutral_grip_pull_up',
  'Pull Up': 'pull_up',
  'Rear Delt Fly (Machine)': 'rear_delt_fly_machine',
  'Seated Lever Machine Row': 'seated_lever_machine_row',
  'Seated Machine Row': 'seated_machine_row',
  'Seated Overhead Press (Barbell)': 'seated_overhead_press_barbell',
  'Sit up': 'sit_up',
  'Smith Calf Raise': 'smith_calf_raise',
  'Stair Master': 'stair_master',
  'Standing Overhead Press (Barbell)': 'barbell_standing_overhead_press',
  'Standing Single Arm Cable Rear Delt Fly': 'standing_single_arm_cable_rear_delt_fly',
  'Standing Two Arm Cable Rear Delt Fly': 'standing_two_arm_cable_rear_delt_fly',
  'Zercher Squat': null,
};